### ISSUE TITLE
Financial Data.ai

### ISSUE THREAD

**Issue by mhewitt72** [virattt/ai-hedge-fund#22]
Is there another option besides the $100 per month subscription to the FinancialData.ai API?

**Comment by virattt** [comment]
You can connect any API that you want.

Just swap out the code in tools/api.py

**Comment by surapuramakhil** [comment]
@virattt feature request to add a provider which as free tier - so that we can explore and play with this project.

**Comment by virattt** [comment]
Go for it.

I'd recommend forking the repo and adding your preferred provider to your projects.

I am using Financial Datasets as I am the creator of the API and trust the data quality.

Also, I am building out the API while building out the AI hedge fund.

**Comment by surapuramakhil** [comment]
@virattt 
In that case, could you consider offering a free tier for your API's? Or at least lowering the minimum credit addition from $20 to $1 or something similar?

**Comment by virattt** [comment]
@surapuramakhil - data for AAPL, NVDA, MSFT, GOOGL, and TSLA is free.

**Comment by surapuramakhil** [comment]
for AAPL

```zsh
(3.12.0) (base) akhilsurapuram@Akhils-MacBook-Pro ai-hedge-fund % poetry run python src/main.py --ticker AAPL --show-reasoning
Traceback (most recent call last):
  File "/Users/akhilsurapuram/openSource/ai-hedge-fund/src/main.py", line 92, in <module>
    result = run_hedge_fund(
        ticker=args.ticker,
    ...<3 lines>...
        show_reasoning=args.show_reasoning
    )
  File "/Users/akhilsurapuram/openSource/ai-hedge-fund/src/main.py", line 19, in run_hedge_fund
    final_state = app.invoke(
        {
    ...<14 lines>...
        },
    )
  File "/Users/akhilsurapuram/Library/Caches/pypoetry/virtualenvs/ai-hedge-fund-OLUHWBl9-py3.13/lib/python3.13/site-packages/langgraph/pregel/__init__.py", line 1929, in invoke
    for chunk in self.stream(
                 ~~~~~~~~~~~^
        input,
        ^^^^^^
    ...<6 lines>...
        **kwargs,
        ^^^^^^^^^
    ):
    ^
  File "/Users/akhilsurapuram/Library/Caches/pypoetry/virtualenvs/ai-hedge-fund-OLUHWBl9-py3.13/lib/python3.13/site-packages/langgraph/pregel/__init__.py", line 1649, in stream
    for _ in runner.tick(
             ~~~~~~~~~~~^
        loop.tasks.values(),
        ^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        get_waiter=get_waiter,
        ^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "/Users/akhilsurapuram/Library/Caches/pypoetry/virtualenvs/ai-hedge-fund-OLUHWBl9-py3.13/lib/python3.13/site-packages/langgraph/pregel/runner.py", line 105, in tick
    run_with_retry(t, retry_policy, writer=writer)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akhilsurapuram/Library/Caches/pypoetry/virtualenvs/ai-hedge-fund-OLUHWBl9-py3.13/lib/python3.13/site-packages/langgraph/pregel/retry.py", line 44, in run_with_retry
    task.proc.invoke(task.input, config)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/akhilsurapuram/Library/Caches/pypoetry/virtualenvs/ai-hedge-fund-OLUHWBl9-py3.13/lib/python3.13/site-packages/langgraph/utils/runnable.py", line 410, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
  File "/Users/akhilsurapuram/Library/Caches/pypoetry/virtualenvs/ai-hedge-fund-OLUHWBl9-py3.13/lib/python3.13/site-packages/langgraph/utils/runnable.py", line 184, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "/Users/akhilsurapuram/openSource/ai-hedge-fund/src/agents/market_data.py", line 28, in market_data_agent
    prices = get_prices(
        ticker=data["ticker"],
        start_date=start_date,
        end_date=end_date,
    )
  File "/Users/akhilsurapuram/openSource/ai-hedge-fund/src/tools/api.py", line 125, in get_prices
    raise Exception(
        f"Error fetching data: {response.status_code} - {response.text}"
    )
Exception: Error fetching data: 402 - {"error":"Insufficient credits","message":"Your current balance is $0.00. Please add more credits to continue using the API."}
During task with name 'market_data_agent' and id '24728e7d-40e5-d8ab-07d1-81b7732532ef'
```
